# Generated by Django 5.1.4 on 2024-12-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "pictures",
                    models.ImageField(blank=True, null=True, upload_to="car_pictures/"),
                ),
                ("description", models.TextField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("sold", "Sold"),
                            ("reserved", "Reserved"),
                        ],
                        default="available",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
