# Generated by Django 5.1.4 on 2025-01-22 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yourcoche", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="pictures",
        ),
        migrations.AlterField(
            model_name="car",
            name="state",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Sold", "Sold"),
                    ("Reserved", "Reserved"),
                ],
                default="Available",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="CarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="car_pictures/")),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="yourcoche.car",
                    ),
                ),
            ],
        ),
    ]
