# Generated by Django 5.1.4 on 2025-01-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yourcoche", "0002_remove_car_pictures_alter_car_state_carimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="pictures",
            field=models.ImageField(blank=True, null=True, upload_to="car_pictures/"),
        ),
        migrations.AlterField(
            model_name="car",
            name="state",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Sold", "Sold"),
                    ("Reserved", "Reserved"),
                ],
                default="available",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="CarImage",
        ),
    ]
