# Generated by Django 5.1.4 on 2025-02-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yourcoche", "0004_remove_car_pictures_remove_car_state_carimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="km",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="motor",
            field=models.CharField(default=1.2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="transmission",
            field=models.CharField(
                choices=[("manual", "Manual"), ("automatic", "Automatic")],
                default="manual",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="year",
            field=models.PositiveIntegerField(default=2013),
            preserve_default=False,
        ),
    ]
