# Generated by Django 5.1.4 on 2025-03-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yourcoche", "0005_car_km_car_motor_car_transmission_car_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carimage",
            name="image",
            field=models.ImageField(upload_to="static/car_images"),
        ),
    ]
