# Generated by Django 5.1.4 on 2025-03-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yourcoche", "0007_alter_carimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carimage",
            name="image",
            field=models.ImageField(upload_to="car_images/"),
        ),
    ]
